image: debian:latest
  
stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - tar -zcvf latest.tar.gz *
    - mv latest.tar.gz /home/gitlab-runner
  only:
    - master

test:
  stage: test
  script:
    - sudo apt-get -q update
    - sudo apt-get -q -y install python3 curl
    - curl https://bootstrap.pypa.io/get-pip.py | sudo python3
    - sudo python3 -m pip install --upgrade pip
    - sudo python3 -m pip install numpy
    - sudo python3 -m pip install --upgrade numpy
    - python3 Qtest.py

deploy:
  stage: deploy
  
  script:
    - sudo apt-get -q update 
    - sudo apt-get -q -y install locales
    - sudo apt-get -q -y install sshpass
    - mv /home/gitlab-runner/latest.tar.gz ./
    - ls -lah
    - sudo chmod 775 Qdeploy.sh
    - ./Qdeploy.sh $QDEPLOYMENT_PASS
  only:
    - master