image: debian:latest
  
stages:
  - build
  - deploy

build:
  stage: build
  script:
    - whoami
    - pwd
    - sudo apt-get update 
    - sudo apt-get -y install locales
    - sudo echo "es_ES.UTF-8 UTF-8"  > /etc/locale.gen && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && locale-gen
    - sudo mkdir /home/quantum/
    - sudo cp -r * /home/quantum/

deploy:
  stage: deploy
  
  script: Qdeploy.sh $QDEPLOYMENT_PASS
  only:
    - master