image: debian:latest
  
stages:
  - build
  - deploy

build:
  stage: build
  script:
    - whoami
    - pwd
    - sudo apt-get -q update 
    - sudo apt-get -q -y install locales
    - sudo apt-get -q -y install sshpass
    - sudo mkdir -p /home/quantum/QSimulator
    - sudo rm -rf /home/quantum/QSimulator/*
    - sudo cp -r * /home/quantum/QSimulator
  only:
    - master

deploy:
  stage: deploy
  
  script:
    - sudo chmod 775 /home/quantum/QSimulator/Qdeploy.sh
    - sudo /home/quantum/QSimulator/Qdeploy.sh $QDEPLOYMENT_PASS
  only:
    - master