image: debian:latest
  
stages:
  - build
  - deploy

build:
  stage: build
  script:
    - tar -zcvf latest.tar.gz *
    - ls -lah
  only:
    - master

deploy:
  stage: deploy
  
  script:
    - sudo apt-get -q update 
    - sudo apt-get -q -y install locales
    - sudo apt-get -q -y install sshpass
    - sudo chmod 775 Qdeploy.sh
    - ls -lah
    - ./Qdeploy.sh $QDEPLOYMENT_PASS
  only:
    - master