image: debian:latest
  
stages:
  - build
  - deploy

build:
  stage: build
  script:
    - whoami
    - pwd
    - sudo apt-get -q update 
    - sudo apt-get -q -y install locales
    - sudo mkdir /home/quantum/
    - sudo cp -r * /home/quantum/

deploy:
  stage: deploy
  
  script: /home/quantum/Qdeploy.sh $QDEPLOYMENT_PASS
  only:
    - master